
import StreamVideoProvider from "@/Providers/StreamClientProvider";
import { Metadata } from "next";
import React, { ReactNode } from "react";

export const metadata: Metadata = {
  title: "⚡VoltMeet⚡",
  description:
    "Generated by create next app, with typescript and tailwind css, Streem.io, Clerk.Auth  for user management and Video React for video chat.",
    icons:"/icons/play.svg" 
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return <main className="relative">
<StreamVideoProvider>
{children}
</StreamVideoProvider>
    </main>;
};

export default RootLayout;
